name: Run Telegram Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * *'  # roda a cada 15 minutos

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install python-telegram-bot --upgrade

      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          python newbot.py
          import asyncio
import os
from telegram import Bot

async def notify_start():
    token = os.getenv("TELEGRAM_BOT_TOKEN")
    chat_id = 1623073007  # Seu ID do Telegram
    bot = Bot(token=token)
    await bot.send_message(chat_id=chat_id, text="✅ Bot do Estilo do Laperuta iniciado com sucesso!")

asyncio.run(notify_start())

